defmodule Arbor.Transport.Socket do
  @moduledoc """
  Phoenix socket adapter generated by `use Arbor.Socket`.

  Application modules should prefer `use Arbor.Socket`; this module owns the
  Phoenix-specific expansion and connect context plumbing.
  """

  # Phoenix socket assign containing the connected Arbor socket context.
  @arbor_socket_key :__arbor_socket__

  @doc """
  Declares the Phoenix socket adapter for an Arbor socket.

  ## Examples

      defmodule MyAppWeb.ArborSocket do
        use Arbor.Socket, roots: [MyApp.Stores.DashboardStore]
      end
  """
  @spec __using__(keyword()) :: Macro.t()
  defmacro __using__(opts) do
    roots =
      opts
      |> Keyword.fetch!(:roots)
      |> Arbor.Socket.__normalize_roots__(__CALLER__)

    quote bind_quoted: [roots: roots] do
      use Phoenix.Socket

      @behaviour Arbor.Socket

      channel("arbor:*", Arbor.Transport.ConnectionChannel)

      @__arbor_roots__ roots

      @impl Arbor.Socket
      def handle_connect(_params, socket), do: {:ok, socket}

      @impl Arbor.Socket
      def handle_join(_params, socket), do: {:ok, socket}

      defoverridable handle_connect: 2, handle_join: 2

      @impl Phoenix.Socket
      def connect(params, phoenix_socket, connect_info) do
        Arbor.Transport.Socket.__connect__(__MODULE__, params, phoenix_socket, connect_info)
      end

      @impl Phoenix.Socket
      def id(_socket), do: nil

      @doc false
      @spec __arbor_roots__() :: Arbor.Socket.roots()
      def __arbor_roots__, do: @__arbor_roots__
    end
  end

  @doc """
  Builds the Arbor socket context for a Phoenix connect callback.

  ## Examples

      iex> socket = Arbor.Transport.Socket.build_connect_socket(%{"token" => "t"}, %{session: %{"user_id" => "u1"}})
      iex> Arbor.Socket.session(socket)
      %{"user_id" => "u1"}
  """
  @spec build_connect_socket(map(), map()) :: Arbor.Socket.t()
  def build_connect_socket(params, connect_info) when is_map(params) and is_map(connect_info) do
    session = Map.get(connect_info, :session, %{})

    %Arbor.Socket{}
    |> Arbor.Socket.put_session(session)
    |> Arbor.Socket.put_connect_info(connect_info)
  end

  @doc false
  @spec __connect__(module(), map(), Phoenix.Socket.t(), map()) ::
          {:ok, Phoenix.Socket.t()} | :error
  def __connect__(socket_module, params, %Phoenix.Socket{} = phoenix_socket, connect_info)
      when is_atom(socket_module) and is_map(params) and is_map(connect_info) do
    arbor_socket = build_connect_socket(params, connect_info)

    case socket_module.handle_connect(params, arbor_socket) do
      {:ok, %Arbor.Socket{} = connected_socket} ->
        {:ok, put_connect_socket(phoenix_socket, connected_socket)}

      :error ->
        :error

      {:error, _reason} ->
        :error
    end
  end

  @doc false
  @spec assign_connect_context(Phoenix.Socket.t(), map(), map()) :: Phoenix.Socket.t()
  def assign_connect_context(%Phoenix.Socket{} = socket, params, connect_info)
      when is_map(params) and is_map(connect_info) do
    put_connect_socket(socket, build_connect_socket(params, connect_info))
  end

  @doc false
  @spec put_connect_socket(Phoenix.Socket.t(), Arbor.Socket.t()) :: Phoenix.Socket.t()
  def put_connect_socket(%Phoenix.Socket{} = socket, %Arbor.Socket{} = arbor_socket) do
    Phoenix.Socket.assign(socket, @arbor_socket_key, arbor_socket)
  end

  @doc false
  @spec fetch_connect_socket(Phoenix.Socket.t()) ::
          {:ok, Arbor.Socket.t()} | {:error, :missing_socket}
  def fetch_connect_socket(%Phoenix.Socket{assigns: assigns}) do
    case Map.fetch(assigns, @arbor_socket_key) do
      {:ok, %Arbor.Socket{} = socket} -> {:ok, socket}
      _other -> {:error, :missing_socket}
    end
  end
end
