defmodule Arbor.Codegen.TypeScript do
  @moduledoc """
  TypeScript codegen for every Arbor `state do` module exposed by the
  current Mix project. Emits a single ambient `.d.ts` bundle.

  ## Output shape

  One file (`priv/codegen/ts/arbor.d.ts` by default) containing:

    * one top-level `namespace <Root>` block (root namespace configurable
      via `config :arbor, :ts_codegen_root_namespace, "Arbor"`) carrying
      shared marker types (`StoreId`, `AsyncResult`, `StoreDef`,
      `StoreField`, `StreamField`, `AsyncField`) and an `interface
      Stores` populated with one entry per Arbor.Store module
    * one top-level `namespace <Path>` block per Arbor.State module,
      nested to mirror the Elixir module tree, each holding an
      `interface <Name> { ... }` declaration

  The file is an ambient `.d.ts` (no top-level `import` / `export`),
  so tsc picks it up automatically when the file falls under the
  project's `include` glob. Consumers reference generated types as e.g.
  `<Root>.Stores`, `MyApp.States.LineItemState`, without any side-effect
  import.

  Consumers thread the generated `<Root>.Stores` type through the
  `@arbor/client` API as the registry generic:

      const cart = await connectStore<MyApp.Stores>(socket, {
        module: "MyApp.Stores.CartPageStore",
        id: "cart:demo"
      })

  ## Type mapping

  | Arbor field type AST            | TypeScript                              |
  | :------------------------------ | :-------------------------------------- |
  | `String.t()` / `binary()`       | `string`                                |
  | `integer()` / `float()`         | `number`                                |
  | `boolean()`                     | `boolean`                               |
  | `atom()`                        | `string` (atoms serialize as strings)   |
  | `:literal` (atom literal)       | `"literal"`                             |
  | `nil`                           | `null`                                  |
  | `map()`                         | `Record<string, unknown>`               |
  | `%{key: T}`                     | `{ key: T }` (literal-keyed map)        |
  | `list(T)` / `[T]`               | `T[]`                                   |
  | `stream(T)`                     | `<Root>.StreamField<T>`                 |
  | `T \\| U`                       | `T \| U`                                |
  | `Module.t()`                    | full Elixir alias path                  |
  | `Module.state()`                | `<Root>.StoreField<"Full.Module">`      |
  | `Arbor.AsyncResult.of(T)`       | `<Root>.AsyncField<T>`                  |
  """

  alias Arbor.Codegen.TypeScript.TypeRenderer

  @default_root "Arbor"

  @typedoc """
  An entry produced by `Arbor.Codegen.TypeScript.Manifest.list/0` and
  consumed by `render/1`. Pre-loaded reflection data — `render/1` performs no
  module-callback lookups itself.
  """
  @type entry() ::
          {module(), %{kind: :state | :store, fields: list(), commands: list()}}

  @doc """
  Renders one TypeScript bundle covering every `{module, data}` entry in
  `entries`. Returns the rendered source string. Raises `ArgumentError` on
  a duplicate fully-qualified module name (defensive — real modules can't
  collide).

  Options:
    * `:root_namespace` — root namespace name. Defaults to
      `Application.get_env(:arbor, :ts_codegen_root_namespace, "Arbor")`.
  """
  @spec render([entry()]) :: String.t()
  @spec render([entry()], keyword()) :: String.t()
  def render(entries, opts \\ []) when is_list(entries) do
    root = Keyword.get(opts, :root_namespace, configured_root_namespace())

    entries =
      entries
      |> Enum.uniq_by(fn {module, _data} -> module end)
      |> Enum.sort_by(fn {module, _data} -> Module.split(module) end)
      |> validate_no_duplicates!()
      |> normalize_kinds()

    {store_entries, state_entries} =
      Enum.split_with(entries, fn {_module, %{kind: kind}} -> kind == :store end)

    iodata = [
      header(),
      root_namespace_block(root, store_entries),
      state_namespaces_block(state_entries, root)
    ]

    IO.iodata_to_binary(iodata)
  end

  @doc """
  Returns the configured root namespace, falling back to `"Arbor"`.
  """
  @spec configured_root_namespace() :: String.t()
  def configured_root_namespace do
    Application.get_env(:arbor, :ts_codegen_root_namespace, @default_root)
  end

  defp header do
    "// Generated by `mix compile.arbor_ts`. Do not edit by hand.\n\n"
  end

  defp validate_no_duplicates!(entries) do
    duplicates =
      entries
      |> Enum.frequencies_by(fn {module, _data} -> Module.split(module) end)
      |> Enum.filter(fn {_path, count} -> count > 1 end)

    case duplicates do
      [] -> entries
      _list -> raise ArgumentError, "duplicate Arbor module paths: #{inspect(duplicates)}"
    end
  end

  defp normalize_kinds(entries) do
    Enum.map(entries, fn {module, data} ->
      kind = Map.get(data, :kind) || :state
      {module, Map.put(data, :kind, kind)}
    end)
  end

  # ---------------------------------------------------------------------------
  # Root namespace
  # ---------------------------------------------------------------------------

  defp root_namespace_block(root, store_entries) do
    [
      "declare namespace ",
      root,
      " {\n",
      shared_marker_types(),
      "\n",
      stores_interface_block(store_entries, root),
      "}\n"
    ]
  end

  defp shared_marker_types do
    """
      type StoreId = string[]

      type AsyncError =
        | { kind: "error"; value: unknown }
        | { kind: "exit"; value: unknown }

      type AsyncResult<T> =
        | { __arbor_async__: true; status: "loading"; result: T | null; reason: null }
        | { __arbor_async__: true; status: "ok"; result: T; reason: null }
        | { __arbor_async__: true; status: "failed"; result: T | null; reason: AsyncError | unknown }

      const Type: unique symbol

      interface StoreDef<Module extends string, Shape, Commands> {
        readonly [Type]: {
          module: Module
          shape: Shape
          commands: Commands
        }
      }

      type StoreField<Module extends string> = {
        readonly [Type]: { kind: "store"; module: Module }
      }

      type StreamField<Item> = {
        readonly [Type]: { kind: "stream"; item: Item }
      }

      type AsyncField<Value> = {
        readonly [Type]: { kind: "async"; value: Value }
      }
    """
  end

  defp stores_interface_block([], _root) do
    "  interface Stores {}\n"
  end

  defp stores_interface_block(store_entries, root) do
    body = Enum.map_join(store_entries, "\n\n", &render_store_def(&1, "    ", root))

    [
      "  interface Stores {\n",
      body,
      "\n",
      "  }\n"
    ]
  end

  defp render_store_def({module, %{fields: fields, commands: commands}}, indent, root) do
    module_name = full_module_name(module)
    shape_indent = indent <> "  "
    field_lines = render_state_fields(fields, shape_indent <> "  ", root)

    [
      indent,
      inspect(module_name),
      ": StoreDef<\n",
      shape_indent,
      inspect(module_name),
      ",\n",
      shape_indent,
      "{\n",
      Enum.join(field_lines, "\n"),
      "\n",
      shape_indent,
      "},\n",
      render_commands_block(commands, shape_indent, root),
      "\n",
      indent,
      ">"
    ]
  end

  defp render_commands_block([], indent, _root), do: [indent, "{}"]

  defp render_commands_block(commands, indent, root) do
    inner_indent = indent <> "  "

    body =
      Enum.map_join(commands, "\n", fn command ->
        render_command_entry(command, inner_indent, root)
      end)

    [indent, "{\n", body, "\n", indent, "}"]
  end

  defp render_command_entry(
         %{name: name, payload_fields: payload_fields} = command,
         indent,
         root
       ) do
    inner_indent = indent <> "  "
    reply_ast = Map.get(command, :reply)

    [
      indent,
      Atom.to_string(name),
      ": {\n",
      inner_indent,
      "payload: ",
      render_command_payload(payload_fields, root),
      "\n",
      inner_indent,
      "reply: ",
      render_reply(reply_ast, root),
      "\n",
      indent,
      "}"
    ]
  end

  defp render_reply(nil, _root), do: "unknown"
  defp render_reply(ast, root), do: TypeRenderer.render(ast, root_namespace: root)

  defp render_command_payload([], _root), do: "{}"

  defp render_command_payload(fields, root) do
    body =
      Enum.map_join(fields, "; ", fn %{name: name, type: type_ast} ->
        "#{name}: #{TypeRenderer.render(type_ast, root_namespace: root)}"
      end)

    "{ " <> body <> " }"
  end

  # ---------------------------------------------------------------------------
  # State namespaces
  # ---------------------------------------------------------------------------

  defp state_namespaces_block([], _root), do: []

  defp state_namespaces_block(state_entries, root) do
    tree = build_state_tree(state_entries)
    body = emit_state_tree(tree, 0, root)

    ["\n", body]
  end

  defp build_state_tree(entries) do
    Enum.reduce(entries, %{}, fn {module, _data} = entry, acc ->
      insert_state_entry(acc, Module.split(module), entry)
    end)
  end

  defp insert_state_entry(tree, [last], entry) do
    Map.update(tree, last, {%{}, entry}, fn {children, _existing} -> {children, entry} end)
  end

  defp insert_state_entry(tree, [head | rest], entry) do
    Map.update(tree, head, {insert_state_entry(%{}, rest, entry), nil}, fn {children, leaf} ->
      {insert_state_entry(children, rest, entry), leaf}
    end)
  end

  defp emit_state_tree(tree, depth, root) do
    tree
    |> Enum.sort_by(fn {segment, _entry} -> segment end)
    |> Enum.map(&emit_state_node(&1, depth, root))
    |> Enum.intersperse("\n")
  end

  defp emit_state_node({segment, {children, nil}}, depth, root) do
    indent = String.duplicate("  ", depth)
    children_body = emit_state_tree(children, depth + 1, root)

    emit_namespace_block(segment, children_body, indent, namespace_keyword(depth))
  end

  # Top-level leaf with no children: wrap in `declare namespace` so the
  # ambient .d.ts file picks it up. Nested leaves stay as bare
  # `interface` declarations inside their parent namespace.
  defp emit_state_node({segment, {children, leaf_entry}}, 0, root)
       when map_size(children) == 0 do
    emit_namespace_block(
      segment,
      render_state_interface(segment, fields_from(leaf_entry), "  ", root),
      "",
      namespace_keyword(0)
    )
  end

  defp emit_state_node({segment, {children, leaf_entry}}, depth, root)
       when map_size(children) == 0 do
    indent = String.duplicate("  ", depth)
    render_state_interface(segment, fields_from(leaf_entry), indent, root)
  end

  defp emit_state_node({segment, {children, leaf_entry}}, depth, root) do
    indent = String.duplicate("  ", depth)
    children_body = emit_state_tree(children, depth + 1, root)

    leaf_interface =
      render_state_interface(segment, fields_from(leaf_entry), indent <> "  ", root)

    emit_namespace_block(
      segment,
      [leaf_interface, children_body],
      indent,
      namespace_keyword(depth)
    )
  end

  defp emit_namespace_block(segment, body, indent, keyword) do
    [indent, keyword, segment, " {\n", body, indent, "}\n"]
  end

  defp namespace_keyword(0), do: "declare namespace "
  defp namespace_keyword(_depth), do: "namespace "

  defp fields_from({_module, %{fields: fields}}), do: fields

  defp render_state_interface(name, fields, indent, root) do
    field_lines = render_state_fields(fields, indent <> "  ", root)

    [
      indent,
      "interface ",
      name,
      " {\n",
      Enum.join(field_lines, "\n"),
      "\n",
      indent,
      "}\n"
    ]
  end

  # ---------------------------------------------------------------------------
  # Shared field rendering
  # ---------------------------------------------------------------------------

  defp render_state_fields(fields, indent, root) do
    fields
    |> filter_renderable_fields()
    |> Enum.map(fn %{name: field_name, type: type_ast} ->
      "#{indent}#{field_name}: #{TypeRenderer.render(type_ast, root_namespace: root)}"
    end)
  end

  defp filter_renderable_fields(fields) do
    Enum.reject(fields, fn %{name: name} -> name in [:__streams__] end)
  end

  defp full_module_name(module) when is_atom(module) do
    module |> Module.split() |> Enum.join(".")
  end
end
