defmodule Arbor.Codegen.TypeScript do
  @moduledoc """
  Pure rendering layer for the `mix arbor.codegen.ts` task. Walks the field
  type AST stored on `Module.__arbor__/1` and emits a TypeScript source string.

  ## Type mapping

  | Arbor field type AST            | TypeScript                              |
  | :------------------------------ | :-------------------------------------- |
  | `String.t()` / `binary()`       | `string`                                |
  | `integer()` / `float()`         | `number`                                |
  | `boolean()`                     | `boolean`                               |
  | `atom()`                        | `string` (atoms serialize as strings)   |
  | `:literal` (atom literal)       | `"literal"`                             |
  | `nil`                           | `null`                                  |
  | `map()`                         | `Record<string, unknown>`               |
  | `%{key: T}`                     | `{ key: T }` (literal-keyed map)        |
  | `list(T)` / `[T]`               | `T[]`                                   |
  | `stream(T)`                     | `T[]` (server forgets values)           |
  | `T \\| U`                       | `T \| U`                                |
  | `Module.t()` / `Module.state()` | TS type alias derived from `Module`     |
  | `Arbor.AsyncResult.of(T)`       | `AsyncResult<T>`                        |

  ## Module-name convention

  The TS alias for an Arbor module is the last alias segment with a `State`
  suffix when the segment does not already end in `State`. Cross-module
  references emit only the alias name; the rendered file always emits the
  shared `AsyncResult<T>` generic so callers can `import` it once.
  """

  alias Arbor.Plugin.Normalize

  @typedoc "Rendered TypeScript source for one Arbor module."
  @type rendered() :: %{path: String.t(), contents: String.t()}

  @async_result_alias "AsyncResult"

  @doc """
  Returns whether `module` is TypeScript-codegen-eligible: it must be an Arbor
  store/state module that opted into the `Arbor.Plugin.TypeScript` plugin.

  ## Examples

      iex> Arbor.Codegen.TypeScript.eligible?(Arbor.TestSupport.TypespecProbe)
      true
      iex> Arbor.Codegen.TypeScript.eligible?(Arbor.Socket)
      false
  """
  @spec eligible?(module()) :: boolean()
  def eligible?(module) when is_atom(module) do
    Code.ensure_loaded?(module) and
      function_exported?(module, :__arbor__, 1) and
      has_ts_attribute?(module)
  end

  @doc """
  Renders one TypeScript file for `module`. Returns `nil` when the module is
  not codegen-eligible.

  ## Examples

      iex> %{path: path, contents: contents} =
      ...>   Arbor.Codegen.TypeScript.render(Arbor.TestSupport.TypespecProbe)
      iex> path
      "TypespecProbeState.ts"
      iex> String.contains?(contents, "export type TypespecProbeState")
      true
  """
  @spec render(module()) :: rendered() | nil
  def render(module) when is_atom(module) do
    if eligible?(module) do
      render_module(module)
    end
  end

  defp render_module(module) do
    state_alias = state_alias(module)
    fields = List.wrap(module.__arbor__(:fields))
    streams = List.wrap(module.__arbor__(:streams))
    commands = List.wrap(module.__arbor__(:commands))

    state_block = render_state_block(state_alias, fields, streams)

    commands_block =
      if commands == [] do
        nil
      else
        render_commands_block(state_alias, commands)
      end

    contents =
      [header(), state_block, commands_block]
      |> Enum.reject(&is_nil/1)
      |> Enum.intersperse("\n")
      |> IO.iodata_to_binary()

    %{path: state_alias <> ".ts", contents: contents}
  end

  @doc """
  Returns the TypeScript alias used for `module`. Suffixes with `State` when
  the trailing segment does not already include it.

  ## Examples

      iex> Arbor.Codegen.TypeScript.state_alias(MyApp.Stores.ProductPageStore)
      "ProductPageStoreState"
      iex> Arbor.Codegen.TypeScript.state_alias(MyApp.MessageState)
      "MessageState"
  """
  @spec state_alias(module()) :: String.t()
  def state_alias(module) when is_atom(module) do
    last =
      module
      |> Module.split()
      |> List.last()

    if String.ends_with?(last, "State"), do: last, else: last <> "State"
  end

  defp header do
    """
    // Generated by `mix arbor.codegen.ts`. Do not edit by hand.

    export type AsyncResult<T> =
      | { status: "loading"; result: T | null; reason: null }
      | { status: "ok"; result: T; reason: null }
      | { status: "failed"; result: T | null; reason: unknown }
    """
  end

  defp render_state_block(state_alias, fields, streams) do
    stream_names = MapSet.new(streams, & &1.name)

    field_lines =
      fields
      |> filter_renderable_fields()
      |> Enum.map(&render_state_field(&1, stream_names))

    """
    export type #{state_alias} = {
    #{Enum.join(field_lines, "\n")}
    }
    """
  end

  defp filter_renderable_fields(fields) do
    Enum.reject(fields, fn %{name: name} ->
      name in [:__streams__]
    end)
  end

  defp render_state_field(%{name: name, type: type_ast}, _stream_names) do
    "  #{name}: #{render_type(type_ast)}"
  end

  defp render_commands_block(state_alias, commands) do
    commands_alias = commands_alias_for(state_alias)

    fields =
      Enum.map(commands, fn %{name: name, payload_fields: payload_fields} ->
        "  #{name}: #{render_command_payload(payload_fields)}"
      end)

    """
    export type #{commands_alias} = {
    #{Enum.join(fields, "\n")}
    }
    """
  end

  defp commands_alias_for(state_alias) do
    state_alias
    |> String.replace_suffix("State", "")
    |> Kernel.<>("Commands")
  end

  defp render_command_payload([]), do: "{}"

  defp render_command_payload(fields) do
    normalized = Normalize.fields(fields)

    body =
      Enum.map_join(normalized, "; ", fn %{name: name, type: type_ast} ->
        "#{name}: #{render_type(type_ast)}"
      end)

    "{ " <> body <> " }"
  end

  # ---------------------------------------------------------------------------
  # Type-AST → TypeScript rendering
  # ---------------------------------------------------------------------------

  @doc """
  Renders a single Arbor field-type AST node as TypeScript.

  ## Examples

      iex> Arbor.Codegen.TypeScript.render_type(quote(do: String.t()))
      "string"
      iex> Arbor.Codegen.TypeScript.render_type(quote(do: list(String.t())))
      "string[]"
      iex> Arbor.Codegen.TypeScript.render_type(quote(do: stream(String.t())))
      "string[]"
      iex> Arbor.Codegen.TypeScript.render_type(quote(do: String.t() | nil))
      "string | null"
  """
  @spec render_type(Macro.t()) :: String.t()
  def render_type(type_ast), do: do_render(type_ast)

  defp do_render({:|, _meta, [left, right]}) do
    do_render(left) <> " | " <> do_render(right)
  end

  defp do_render({:list, _meta, [inner]}), do: wrap_array(do_render(inner))
  defp do_render({:stream, _meta, [inner]}), do: wrap_array(do_render(inner))

  defp do_render({:map, _meta, []}), do: "Record<string, unknown>"

  defp do_render({:string, _meta, []}), do: "string"
  defp do_render({:binary, _meta, []}), do: "string"
  defp do_render({:integer, _meta, []}), do: "number"
  defp do_render({:float, _meta, []}), do: "number"
  defp do_render({:boolean, _meta, []}), do: "boolean"
  defp do_render({:atom, _meta, []}), do: "string"

  # `String.t()` is the most common alias-form shortcut and must be matched
  # before the literal-keyed map clause (whose 3-tuple shape would otherwise
  # capture this AST with `pairs=[]`).
  defp do_render({{:., _dot, [{:__aliases__, _meta, [:String]}, :t]}, _call, []}), do: "string"

  # `Arbor.AsyncResult.of(T)` — exact match on Arbor.AsyncResult.
  defp do_render({{:., _dot, [aliased, :of]}, _call, [inner]}) do
    if async_result_alias?(aliased) do
      "#{@async_result_alias}<#{do_render(inner)}>"
    else
      "unknown"
    end
  end

  # `Module.t()` / `Module.state()` cross-module reference.
  defp do_render({{:., _dot, [aliased, kind]}, _call, []}) when kind in [:t, :state] do
    aliased
    |> trailing_alias_segment()
    |> append_state_suffix()
  end

  defp do_render({:%{}, _meta, pairs}) when is_list(pairs) do
    body =
      Enum.map_join(pairs, "; ", fn {key, value} ->
        "#{render_key(key)}: #{do_render(value)}"
      end)

    "{ " <> body <> " }"
  end

  defp do_render(nil), do: "null"
  defp do_render(true), do: "true"
  defp do_render(false), do: "false"

  defp do_render(literal) when is_atom(literal) do
    inspect(Atom.to_string(literal))
  end

  defp do_render(literal) when is_binary(literal), do: inspect(literal)
  defp do_render(literal) when is_integer(literal), do: Integer.to_string(literal)
  defp do_render(literal) when is_float(literal), do: Float.to_string(literal)

  defp do_render(_other), do: "unknown"

  defp wrap_array(rendered) do
    if String.contains?(rendered, " | ") or String.contains?(rendered, " & ") do
      "Array<#{rendered}>"
    else
      rendered <> "[]"
    end
  end

  defp render_key(key) when is_atom(key), do: Atom.to_string(key)
  defp render_key(key) when is_binary(key), do: inspect(key)

  defp trailing_alias_segment({:__aliases__, _meta, parts}) when is_list(parts) do
    parts |> List.last() |> Atom.to_string()
  end

  defp trailing_alias_segment(module) when is_atom(module) do
    module |> Module.split() |> List.last()
  end

  defp append_state_suffix(name) do
    if String.ends_with?(name, "State"), do: name, else: name <> "State"
  end

  defp async_result_alias?({:__aliases__, _meta, [:Arbor, :AsyncResult]}), do: true
  defp async_result_alias?(Arbor.AsyncResult), do: true
  defp async_result_alias?(_other), do: false

  defp has_ts_attribute?(module) do
    case Keyword.get(module.__info__(:attributes), :__arbor_ts__) do
      nil -> false
      [] -> false
      _value -> true
    end
  end
end
