defmodule Arbor.Codegen.TypeScriptTest do
  use ExUnit.Case, async: true

  alias Arbor.Codegen.TypeScript
  alias Arbor.Codegen.TypeScript.Manifest
  alias Arbor.TestSupport.TypespecProbe
  alias Arbor.TestSupport.TypespecProbeChild
  alias Arbor.TestSupport.TypespecProbeWithCommand

  defp entry(module) do
    data = Manifest.collect(module.__env__())
    {data.module, Map.take(data, [:fields, :commands])}
  end

  # Strip leading whitespace from every line so assertions exercise the line
  # CONTENT (and ordering) without coupling to indentation depth.
  defp normalize(s) do
    s
    |> String.split("\n")
    |> Enum.map_join("\n", &String.trim_leading/1)
  end

  @preamble """
  // Generated by `mix compile.arbor_ts`. Do not edit by hand.

  export type AsyncResult<T> =
    | { status: "loading"; result: T | null; reason: null }
    | { status: "ok"; result: T; reason: null }
    | { status: "failed"; result: T | null; reason: unknown }
  """

  describe "render/1 — empty" do
    test "renders just the preamble (no namespaces)" do
      expected = @preamble <> "\n"
      assert normalize(TypeScript.render([])) == normalize(expected)
    end
  end

  describe "render/1 — Arbor.State module (no commands)" do
    test "single nested module emits the namespace tree + type, no Commands" do
      expected =
        @preamble <>
          """

          export namespace Arbor {
            export namespace TestSupport {
              export type TypespecProbeChild = {
                __arbor_store_id__: readonly string[]
                amount: number
              }
            }
          }

          declare module "@arbor/client" {
            interface ArborStoreMap {
              "Arbor.TestSupport.TypespecProbeChild": {
                state: {
                  __arbor_store_id__: readonly string[]
                  amount: number
                }
                commands: {}
              }
            }
          }
          """

      assert normalize(TypeScript.render([entry(TypespecProbeChild)])) == normalize(expected)
    end
  end

  describe "render/1 — Arbor.Store with commands" do
    test "store with commands emits an adjacent Commands namespace" do
      expected =
        @preamble <>
          """

          export namespace Arbor {
            export namespace TestSupport {
              export type TypespecProbeWithCommand = {
                __arbor_store_id__: readonly string[]
                selected_id: string | null
              }

              export namespace TypespecProbeWithCommand {
                export type Commands = {
                  select: { id: string }
                  refresh: {}
                }
              }
            }
          }

          declare module "@arbor/client" {
            interface ArborStoreMap {
              "Arbor.TestSupport.TypespecProbeWithCommand": {
                state: {
                  __arbor_store_id__: readonly string[]
                  selected_id: string | null
                }
                commands: {
                  select: { id: string }
                  refresh: {}
                }
              }
            }
          }
          """

      assert normalize(TypeScript.render([entry(TypespecProbeWithCommand)])) ==
               normalize(expected)
    end
  end

  describe "render/1 — multiple modules" do
    test "siblings under the same parent share namespace" do
      expected =
        @preamble <>
          """

          export namespace Arbor {
            export namespace TestSupport {
              export type TypespecProbe = {
                __arbor_store_id__: readonly string[]
                messages: string[]
                items: Arbor.TestSupport.TypespecProbeChild[]
                load_stream: AsyncResult<Arbor.TestSupport.TypespecProbeChild[]>
                profile: AsyncResult<Arbor.TestSupport.TypespecProbeChild>
                status: { type: "active" } | { type: "paused"; value: number }
                child: Arbor.TestSupport.TypespecProbeChild
                tags: string[]
              }

              export type TypespecProbeChild = {
                __arbor_store_id__: readonly string[]
                amount: number
              }
            }
          }

          declare module "@arbor/client" {
            interface ArborStoreMap {
              "Arbor.TestSupport.TypespecProbe": {
                state: {
                  __arbor_store_id__: readonly string[]
                  messages: string[]
                  items: Arbor.TestSupport.TypespecProbeChild[]
                  load_stream: AsyncResult<Arbor.TestSupport.TypespecProbeChild[]>
                  profile: AsyncResult<Arbor.TestSupport.TypespecProbeChild>
                  status: { type: "active" } | { type: "paused"; value: number }
                  child: Arbor.TestSupport.TypespecProbeChild
                  tags: string[]
                }
                commands: {}
              }
              "Arbor.TestSupport.TypespecProbeChild": {
                state: {
                  __arbor_store_id__: readonly string[]
                  amount: number
                }
                commands: {}
              }
            }
          }
          """

      contents = TypeScript.render([entry(TypespecProbe), entry(TypespecProbeChild)])
      assert normalize(contents) == normalize(expected)
    end

    test "input order doesn't affect output (sorted alphabetically by Module.split)" do
      forward = TypeScript.render([entry(TypespecProbe), entry(TypespecProbeChild)])
      reversed = TypeScript.render([entry(TypespecProbeChild), entry(TypespecProbe)])
      assert forward == reversed
    end
  end

  describe "render/1 — ArborStoreMap augmentation" do
    test "every rendered state includes the runtime store id field" do
      rendered = TypeScript.render([entry(TypespecProbeChild)])

      assert rendered =~ "__arbor_store_id__: readonly string[]"
    end
  end
end
