defmodule Arbor.Codegen.TypeScriptTest do
  use ExUnit.Case, async: true

  alias Arbor.Codegen.TypeScript
  alias Arbor.Codegen.TypeScript.Manifest
  alias Arbor.TestSupport.TypespecProbe
  alias Arbor.TestSupport.TypespecProbeChild
  alias Arbor.TestSupport.TypespecProbeWithCommand

  defp entry(module) do
    data = Manifest.collect(module.__env__())
    {data.module, Map.take(data, [:kind, :fields, :commands])}
  end

  # Strip leading whitespace from every line so assertions exercise the line
  # CONTENT (and ordering) without coupling to indentation depth.
  defp normalize(s) do
    s
    |> String.split("\n")
    |> Enum.map_join("\n", &String.trim_leading/1)
  end

  @preamble """
  // Generated by `mix compile.arbor_ts`. Do not edit by hand.

  declare global {
    namespace Arbor {
      type StoreId = string[]

      type AsyncError =
        | { kind: "error"; value: unknown }
        | { kind: "exit"; value: unknown }

      type AsyncResult<T> =
        | { status: "loading"; data: T | null; error: null }
        | { status: "ok"; data: T; error: null }
        | { status: "failed"; data: T | null; error: AsyncError | unknown }

      interface StoreDef<Module extends string, Shape, Commands> {
        readonly __arbor__module__?: Module
        readonly __arbor__shape__?: Shape
        readonly __arbor__commands__?: Commands
      }

      type StoreField<Module extends string> = {
        readonly __arbor__kind__?: "store"
        readonly __arbor__module__?: Module
      }

      type StreamField<Item> = {
        readonly __arbor__kind__?: "stream"
        readonly __arbor__item__?: Item
      }

      type AsyncField<Value> = {
        readonly __arbor__kind__?: "async"
        readonly __arbor__value__?: Value
      }
  """

  describe "render/1 — empty" do
    test "renders just the preamble with an empty Stores interface" do
      expected = @preamble <> """

          interface Stores {}
        }
      }

      export {}
      """

      assert normalize(TypeScript.render([])) == normalize(expected)
    end
  end

  describe "render/1 — Arbor.Store entry" do
    test "store without commands populates Arbor.Stores with an empty commands map" do
      expected = @preamble <> """

          interface Stores {
            "Arbor.TestSupport.TypespecProbeChild": StoreDef<
              "Arbor.TestSupport.TypespecProbeChild",
              {
                amount: number
              },
              {}
            >
          }
        }
      }

      export {}
      """

      assert normalize(TypeScript.render([entry(TypespecProbeChild)])) == normalize(expected)
    end

    test "store with commands emits payload + reply schema per command" do
      expected = @preamble <> """

          interface Stores {
            "Arbor.TestSupport.TypespecProbeWithCommand": StoreDef<
              "Arbor.TestSupport.TypespecProbeWithCommand",
              {
                selected_id: string | null
              },
              {
                select: {
                  payload: { id: string }
                  reply: unknown
                }
                refresh: {
                  payload: {}
                  reply: unknown
                }
              }
            >
          }
        }
      }

      export {}
      """

      assert normalize(TypeScript.render([entry(TypespecProbeWithCommand)])) ==
               normalize(expected)
    end
  end

  describe "render/1 — multiple modules" do
    test "stores share Arbor.Stores; phantom markers project special fields" do
      rendered = TypeScript.render([entry(TypespecProbe), entry(TypespecProbeChild)])

      # Both stores appear in Arbor.Stores
      assert rendered =~ ~s["Arbor.TestSupport.TypespecProbe": StoreDef<]
      assert rendered =~ ~s["Arbor.TestSupport.TypespecProbeChild": StoreDef<]

      # stream(T) -> StreamField, nested store ref -> StoreField,
      # AsyncResult.of(stream(T)) -> AsyncField<StreamField<T>>
      assert rendered =~ "messages: Arbor.StreamField<string>"
      assert rendered =~ "items: Arbor.StreamField<Arbor.TestSupport.TypespecProbeChild>"
      assert rendered =~
               "load_stream: Arbor.AsyncField<Arbor.StreamField<Arbor.TestSupport.TypespecProbeChild>>"

      assert rendered =~
               "profile: Arbor.AsyncField<Arbor.TestSupport.TypespecProbeChild>"

      assert rendered =~
               ~s|child: Arbor.StoreField<"Arbor.TestSupport.TypespecProbeChild">|

      assert rendered =~ "tags: string[]"

      # Generated stores never embed __arbor_store_id__ in the declared shape;
      # the runtime member is added by the client proxy.
      refute rendered =~ "__arbor_store_id__"

      # Old "declare module \"@arbor/client\"" augmentation is gone.
      refute rendered =~ ~s|declare module "@arbor/client"|
    end

    test "input order doesn't affect output (sorted alphabetically by Module.split)" do
      forward = TypeScript.render([entry(TypespecProbe), entry(TypespecProbeChild)])
      reversed = TypeScript.render([entry(TypespecProbeChild), entry(TypespecProbe)])
      assert forward == reversed
    end
  end

  describe "render/1 — bundle is a module" do
    test "trailing `export {}` makes the bundle a module" do
      rendered = TypeScript.render([entry(TypespecProbeChild)])
      assert String.ends_with?(rendered, "export {}\n")
    end
  end
end
