defmodule Arbor.Hooks.ValidateRender do
  @moduledoc """
  Validates a store's wire-form render output against the compile-time
  `__arbor_validate_state__/1` predicate generated by `Arbor.Plugin.StateField`.
  Runtime-injected reserved keys like `__arbor_store_id__` are ignored.

  Attached to the `:after_serialize` lifecycle stage. Two modes:

    * `:raise` — raise `ArgumentError` on validation failure (dev/test default).
    * `:telemetry` — emit `[:arbor, :validate, :exception]` and continue
      (production default).

  Successful validation emits `[:arbor, :validate, :stop]`.
  """

  alias Arbor.Resolver
  alias Arbor.Socket

  @type validation_mode() :: :raise | :telemetry
  @type validation_error() :: {String.t(), String.t()}

  @doc """
  Runs the per-store validator on the wire-form `render/1` output.

  ## Examples

      socket = %Arbor.Socket{module: MyApp.RootStore}
      Arbor.Hooks.ValidateRender.after_serialize(:raise, %{"title" => "Inbox"}, socket)
      #=> {:cont, socket}
  """
  @spec after_serialize(validation_mode(), term(), Socket.t()) :: Arbor.Lifecycle.hook_result()
  def after_serialize(mode, wire_term, %Socket{module: store_module} = socket)
      when mode in [:raise, :telemetry] and is_atom(store_module) do
    case validate(wire_term, store_module) do
      :ok ->
        emit_stop(store_module)
        {:cont, socket}

      {:error, errors} ->
        emit_exception(store_module, errors)

        case mode do
          :raise -> raise ArgumentError, format_errors(store_module, errors)
          :telemetry -> {:cont, socket}
        end
    end
  end

  @doc """
  Validates a wire-form term against `store_module.__arbor_validate_state__/1`.

  ## Examples

      Arbor.Hooks.ValidateRender.validate(%{"title" => "Inbox"}, MyApp.RootStore)
      #=> :ok
  """
  @spec validate(term(), module()) :: :ok | {:error, [validation_error()]}
  def validate(wire_term, store_module) when is_atom(store_module) do
    if function_exported?(store_module, :__arbor_validate_state__, 1) do
      wire_term
      |> drop_runtime_keys()
      |> store_module.__arbor_validate_state__()
    else
      :ok
    end
  end

  defp drop_runtime_keys(%{} = map) do
    map
    |> Map.delete(Atom.to_string(Resolver.store_id_key()))
    |> Enum.into(%{}, fn {key, value} -> {key, drop_runtime_keys(value)} end)
  end

  defp drop_runtime_keys(list) when is_list(list), do: Enum.map(list, &drop_runtime_keys/1)
  defp drop_runtime_keys(other), do: other

  defp emit_stop(store_module) do
    :telemetry.execute(
      [:arbor, :validate, :stop],
      %{count: 1},
      %{store_module: store_module, errors: []}
    )
  end

  defp emit_exception(store_module, errors) do
    :telemetry.execute(
      [:arbor, :validate, :exception],
      %{count: 1},
      %{store_module: store_module, errors: errors}
    )
  end

  defp format_errors(store_module, errors) do
    details =
      Enum.map_join(errors, "; ", fn {path, message} -> "#{path}: #{message}" end)

    "render output validation failed for #{inspect(store_module)}: #{details}"
  end
end
